[project]
name = "af3io"
version = "26.1-dev"
description = "Eclectic utilities for AlphaFold 3"
readme = "README.md"
authors = [
  { name = "jurgjn", email = "jurgjn@users.noreply.github.com" }
]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
]
dependencies = [
  "click",
  "humanfriendly",
  "scipy",
  "pandas",
  "zarr",
  "biopython",
]

[project.scripts]
af3io = "af3io.cli:cli"

[project.urls]
repository = "https://github.com/jurgjn/af3io"
changelog = "https://github.com/jurgjn/af3io/blob/main/CHANGELOG.md"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
